#!/bin/bash
#
#
# ARG_OPTIONAL_SINGLE([pythonpath],[p],[The path to the python interpreter])
# ARG_HELP([The general script's help msg])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info


die()
{
	local _ret="${2:-1}"
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	echo "$1" >&2
	exit "${_ret}"
}


begins_with_short_option()
{
	local first_option all_short_options='ph'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_pythonpath=


print_help()
{
	printf '%s\n' "The general script's help msg"
	printf 'Usage: %s [-p|--pythonpath <arg>] [-h|--help]\n' "$0"
	printf '\t%s\n' "-p, --pythonpath: The path to the python interpreter (no default)"
	printf '\t%s\n' "-h, --help: Prints help"
}


parse_commandline()
{
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-p|--pythonpath)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_pythonpath="$2"
				shift
				;;
			--pythonpath=*)
				_arg_pythonpath="${_key##--pythonpath=}"
				;;
			-p*)
				_arg_pythonpath="${_key##-p}"
				;;
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			*)
				_PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
				;;
		esac
		shift
	done
}

parse_commandline "$@"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash


# echoerr used for outputting any diagnostic info
echoerr() { echo "$@" 1>&2; }

# Use user supplied python path if provided, otherwise default to system python3
if ! [ "$_arg_pythonpath" == "" ]; then
    pythonpath="$_arg_pythonpath"
else
    pythonpath=$(which python3)
fi

#
if [ "$pythonpath" == "" ]; then
    echoerr "Python not found: please use -p, --pythonpath to specify the path to a python interpreter"
else
    echoerr "Found python at $pythonpath"
fi

python3_version=$($pythonpath --version 2>&1 | awk '{print $2}')
echo ${python3_version}
#if ! echo "$python3_version" | grep -qE '^3\.10|^3\.11|^3\.12' ; then
#  echo -e "${RED}Fatal: Python 3.10 - 3.12 is not installed. Please install.${NC}"
#  exit 1
#fi

# ] <-- needed because of Argbash
